import { debugLog, debugWarn } from '@/lib/logger';

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { surveyToDbSurvey } from '@/utils/type-mappers';
import { Survey } from '@/types/survey';
import { useAuth } from '@/providers/AuthProvider';
import { toast } from '@/components/ui/sonner';

export function useMutateSurvey() {
  const queryClient = useQueryClient();
  const { refreshSession } = useAuth();

  const createSurvey = useMutation({
    mutationFn: async ({ name, folderId }: { name: string, folderId?: string }) => {
      try {
        // Ensure session is fresh before creating survey
        await refreshSession();
        
        const newSurvey: Partial<Survey> = {
          title: name,
          folderId: folderId,
          description: '',
          questions: [],
          isPublished: false
        };

        // Convert to DB format
        const dbSurvey = surveyToDbSurvey(newSurvey as Survey);

        const { data, error } = await supabase
          .from('surveys')
          .insert([{
            name: dbSurvey.name,
            folder_id: dbSurvey.folder_id,
            description: dbSurvey.description || '',
            questions: dbSurvey.questions || [],
            is_published: dbSurvey.is_published || false
            // Note: public_code will be auto-generated by the database trigger if needed
          }])
          .select()
          .single();

        if (error) {
          console.error("Supabase error details:", error);
          if (error.code === '23503') {
            throw new Error('The selected folder does not exist');
          } else if (error.message?.includes("relation \"public.surveys\" does not exist")) {
            throw new Error("The surveys table doesn't exist in the Supabase database. Please create the required tables first.");
          } else if (error.message?.includes("violates row-level security policy")) {
            throw new Error("Authentication error: Please sign out and sign in again to refresh your session.");
          }
          throw new Error(`Database error: ${error.message}`);
        }

        if (!data) {
          throw new Error('No data returned from survey creation');
        }

        return data;
      } catch (err) {
        console.error("Error in createSurveyMutation:", err);
        throw err;
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['surveys'] });
      toast("Survey created successfully");
    },
    onError: (error: Error) => {
      toast("Failed to create survey", { description: error.message || "Unknown error" });
    }
  });

  const updateSurvey = useMutation({
    mutationFn: async ({ surveyId, updates }: { 
      surveyId: string; 
      updates: Partial<Survey>
    }) => {
      try {
        debugLog(`Updating survey with ID: ${surveyId}`);
        debugLog("Updates:", updates);
        
        if (!surveyId) {
          throw new Error('Survey ID is required for updates');
        }
        
        // Convert the updates to database format
        const dbUpdates = surveyToDbSurvey(updates as Survey);
        
        // Remove undefined values and id from updates
        const cleanedUpdates = Object.fromEntries(
          Object.entries(dbUpdates).filter(([key, value]) => value !== undefined && key !== 'id')
        );

        debugLog("Cleaned DB updates:", cleanedUpdates);

        // Ensure we have a fresh session
        await refreshSession();

        // Special handling for publishing: let the database generate the public_code if needed
        if (updates.isPublished && !updates.publicCode) {
          debugLog("Publishing survey without existing public code - database will generate one");
        }

        const { data, error } = await supabase
          .from('surveys')
          .update(cleanedUpdates)
          .eq('id', surveyId)
          .select()
          .single();

        if (error) {
          console.error(`Supabase update error for survey ${surveyId}:`, error);
          
          if (error.message?.includes("violates row-level security policy")) {
            throw new Error("Permission denied: You don't have access to update this survey. Please check your permissions.");
          } else if (error.code === '23503') {
            throw new Error('Invalid folder or team reference');
          } else if (error.code === '42501') {
            throw new Error('Insufficient permissions to update this survey');
          } else if (error.code === '23505' && error.message?.includes('surveys_public_code_unique')) {
            throw new Error('Public code conflict detected. Please try again - a new unique code will be generated.');
          }
          
          throw new Error(`Database error: ${error.message}`);
        }
        
        if (!data) {
          throw new Error('No data returned from survey update');
        }

        debugLog(`Survey ${surveyId} updated successfully:`, data);
        return data;
      } catch (err) {
        console.error(`Error in updateSurveyMutation for survey ${surveyId}:`, err);
        throw err;
      }
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['surveys'] });
      queryClient.invalidateQueries({ queryKey: ['survey', variables.surveyId] });
      debugLog(`Survey ${variables.surveyId} update successful, queries invalidated`);
    },
    onError: (error: Error, variables) => {
      console.error(`Survey ${variables.surveyId} update failed:`, error);
    }
  });

  const deleteSurvey = useMutation({
    mutationFn: async (surveyId: string) => {
      try {
        debugLog(`Deleting survey ${surveyId}`);
        
        const { error } = await supabase
          .from('surveys')
          .delete()
          .eq('id', surveyId);

        if (error) {
          if (error.message?.includes("relation \"public.surveys\" does not exist")) {
            throw new Error("The surveys table doesn't exist in the Supabase database");
          }
          throw new Error(`Database error: ${error.message}`);
        }
        
        debugLog(`Survey ${surveyId} deleted successfully`);
      } catch (err) {
        console.error(`Error in deleteSurveyMutation for survey ${surveyId}:`, err);
        throw err;
      }
    },
    onSuccess: (_, surveyId) => {
      queryClient.removeQueries({ queryKey: ['survey', surveyId] });
      queryClient.invalidateQueries({ queryKey: ['surveys'] });
      debugLog(`Survey ${surveyId} deletion successful, queries invalidated`);
    }
  });

  return {
    createSurvey: createSurvey.mutateAsync,
    updateSurvey: updateSurvey.mutateAsync,
    deleteSurvey: deleteSurvey.mutateAsync
  };
}
